# Generated by Django 2.1.7 on 2020-04-17 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200417_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 8, 27, 869657)),
        ),
    ]
